[package]
name = "rmk-fs"
version = "0.1.0"
edition = "2021"


[dependencies]
datafusion = "7"
fuser = "0.11"
glob = "0.3"
thiserror = "1"
# https://arrow.apache.org/datafusion/user-guide/library.html
# snmalloc-rs = "0.2"
tokio = { version = "1", features = ["rt-multi-thread"] }
